runtime: go
api_version: go1

threadsafe: true
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic

handlers:
- url: /(.*\.html)$
  static_files: \1
  upload: .*\.html$

- url: /img
  static_dir: img

- url: /task.*
  script: _go_app
  login: admin
  secure: always

- url: /.*
  script: _go_app
  secure: always
